### ISSUE TITLE
[BUG] BackLink causes error when using model_json_schema()

### ISSUE THREAD

**Issue by gdlmx** [BeanieODM/beanie#1008]
**Describe the bug**
Generating Json Schema from a document with a `BackLink` field will fail with the error: `PydanticInvalidForJsonSchema`.

**To Reproduce**
```python
from typing import List
from pydantic import Field
from beanie import Document, Link, BackLink

class Task(Document):
    detail: str
    owner:  Link["User"]

class User(Document):
    name: str
    tasks: List[BackLink["Task"]] = Field(json_schema_extra={"original_field": "owner"})

User.model_json_schema()
```

The last line will raise error:

```python
PydanticInvalidForJsonSchema: Cannot generate a JsonSchema for core_schema.PlainValidatorFunctionSchema ({'type': 'with-info', 'function': <function BackLink.build_validation.<locals>.validate at 0x7f89140bdd00>})
```

**Expected behavior**
The last line (model_json_schema) should return 

```json
{
  "properties": {
    "_id": { "...":"..." },
    "name": {  "title": "Name",  "type": "string"  },
    "tasks": { "...":"..." }
  },
  "required": [ "name", "tasks" ],
  "title": "User",
  "type": "object"
}
```

**Additional context**
Python version: 3.11
Beanie version: 1.26.0
Pydantic version: 2.8.2

**Comment by gdlmx** [comment]
Possible cause of this error:

https://github.com/BeanieODM/beanie/blob/bdb6a8692c87ff289c61e6b7df608e30767a94d8/beanie/odm/fields.py#L409-L430

See this [discussion](https://stackoverflow.com/a/77105412/11122845) of a similar error with Pydantic v2.4

**Comment by adeelsohailahmed** [comment]
Thanks for reporting the issue, and taking the time to investigate the cause. Would you like to send a PR to fix this issue, @gdlmx?

**Comment by xalien10** [comment]
@adeelsohailahmed @gdlmx Any updated about this fix yet?

**Comment by gdlmx** [comment]
> Thanks for reporting the issue, and taking the time to investigate the cause. Would you like to send a PR to fix this issue, @gdlmx?

Yes, I can prepare a PR to fix it. Could you provide me some idea about the proper json schema for BackLink?

There is no guarantee of any field in a BackLink object, is there?

**Comment by adeelsohailahmed** [comment]
> There is no guarantee of any field in a BackLink object, is there?

I'm not sure if I fully understand your question here. Could you elaborate more?

**Comment by xalien10** [comment]
@gdlmx is there any update about the PR? :-)
