### ISSUE TITLE
[BUG] project method for find query doesn't work

### ISSUE THREAD

**Issue by hagd0520** [BeanieODM/beanie#1016]
**Describe the bug**
project method for find query doesn't work. It only return the whole Document instead and is same with projection_model parameter in find method.

**To Reproduce**
code below returns whole Document.
```python

class UpdatedAtResponse(BaseModel):
    id: Annotated[PydanticObjectId, Field(validation_alias=AliasChoices('id', "_id"))]
    updatedAt: datetime

await Article.find().project(UpdatedAtResponse).to_list()
```

It works only if i get this through with Settings, projection config like below code as written in beanie official document
```python
class ProductView(BaseModel):
    name: str
    category: str

    class Settings:
        projection = {"name": 1, "category": "$category.name"}
```

**Expected behavior**
I hope project method works properly.

**Comment by staticxterm** [comment]
Hi, thank you for the report.
I'm unable to reproduce this. Please provided a minimum reproducible example that is fully runnable.
`ProductView` is not a proper `View` class with Beanie required fields: `source`, `pipeline`.
