### ISSUE TITLE
Validation Issue with Telegram ID in Indexed Fields

### ISSUE THREAD

**Issue by amirrnazemi** [BeanieODM/beanie#1082]
Hello,

I encountered an issue while using Beanie with a model that has a `telegram_id` field defined as an `Indexed` unique field. The issue arises when attempting to query or validate this field in a specific use case. Below is an example demonstrating the problem:

**Code example:**

```python
from aiogram import BaseMiddleware
from aiogram.types import Message, CallbackQuery
from models import User

class AuthMiddleware(BaseMiddleware):
    async def __call__(self, handler, event, data):
        user_id = None
        if isinstance(event, Message) and event.from_user:
            user_id = str(event.from_user.id)
        elif isinstance(event, CallbackQuery) and event.from_user:
            user_id = str(event.from_user.id)
        
        if user_id:
            # This line raises an AttributeError
            user = await User.find_one(User.telegram_id == user_id)
            
            data['user'] = user
        else:
            data['user'] = None
        
        return await handler(event, data)
```

**Error message:**
```
AttributeError: telegram_id
```

**Steps to reproduce:**

1. Define a `User` model with the `telegram_id` field as an indexed field:
   ```python
   from typing import Annotated
   from beanie import Document, Indexed
   from pydantic import Field

   class User(Document):
       telegram_id: Annotated[str, Indexed(unique=True)] = Field(..., description="Telegram user ID")
   ```
2. Use the above middleware to query a user based on their `telegram_id`.
3. Observe the error raised during execution.

**Expected behavior:**

The `find_one` query should work without raising an `AttributeError` for the `telegram_id` field.

**Actual behavior:**

An `AttributeError` is raised, suggesting that the `telegram_id` attribute is either not properly recognized or is missing.

**Environment:**
- Python version: `...`
- Beanie version: `...`
- MongoDB version: `...`

**Additional context:**

The problem seems related to the `Indexed` functionality for the `telegram_id` field. If there are specific configurations or requirements for this, please provide guidance. Otherwise, I hope this issue can be resolved. 

Thank you for your time and assistance!

**Comment by dikuchan** [comment]
@amirrnazemi Hi! Could you please check if you've initialized the model properly? I encountered this error when I didn't specify document models in the `init_beanie` call:
```python
await beanie.init_beanie(database=database, document_models=[])
```

When `User` is provided, it runs properly.
```python
await beanie.init_beanie(database=database, document_models=[User])
```

**Comment by amirrnazemi** [comment]
Hi @dikuchan,

Thank you for your response! I appreciate your suggestion. However, the issue doesn't seem to be related to the initialization of the `User` model. I've already initialized it correctly in my code using the following:

```python
await init_beanie(database=database, document_models=[User])
```

The problem occurs when executing this condition in the middleware:
```python
user = await User.find_one(User.telegram_id == user_id)
```

The `telegram_id` comparison is causing unexpected behavior. This issue seems to be related to how Beanie handles the equality condition in the query. I suspect there might be a misinterpretation or bug in the query syntax.

Let me know if you have any additional insights or suggestions. Thanks again for taking the time to help!

**Comment by adeelsohailahmed** [comment]
Does the same query work outside of the middleware? Could you share your middleware code with us, please? And where are you initializing the Beanie models?

**Comment by amirrnazemi** [comment]
The code for the project is publicly available in the **Trellogram** repository. You can access the relevant files under the **middlewares** and **models** directories.

To answer your question:  
- Yes, the same query works outside of the middleware.  
- The middleware code and the initialization of the Beanie models are as follows:

**Middleware Code:**  
You can find the middleware implementation in the `middlewares` folder, specifically in the file responsible for authentication. Here's an example of the code:  

```python
from aiogram import BaseMiddleware
from aiogram.types import Message, CallbackQuery
from models.user import User

class AuthMiddleware(BaseMiddleware):
    async def __call__(self, handler, event, data):
        user_id = None
        if isinstance(event, Message) and event.from_user:
            user_id = str(event.from_user.id)
        elif isinstance(event, CallbackQuery) and event.from_user:
            user_id = str(event.from_user.id)
        
        if user_id:
            # Querying the database for the user
            data['user'] = await User.find_one(User.telegram_id == user_id)
        else:
            data['user'] = None

        return await handler(event, data)
```

**Beanie Model Initialization:**  
The Beanie models are initialized in a separate function. You can find this in the project's database utility module. Here's an example snippet:  

```python
from beanie import init_beanie
from motor.motor_asyncio import AsyncIOMotorClient
from models.user import User
from models.map_list import Map_List
from models.map_card import Map_Card

async def init_db():
    client = AsyncIOMotorClient("YOUR_MONGO_URI")
    await init_beanie(
        database=client.get_default_database(),
        document_models=[User, Map_List, Map_Card]
    )
```

This function is called at the start of the bot in the `main` function to ensure the database connection is established and models are initialized.  

Feel free to check the repository for more details or specific code snippets.

**Comment by amirrnazemi** [comment]
The issue has been resolved. The problem was due to the use of a deprecated function for interacting with MongoDB in a different library. After updating the code to call the correct and updated function, everything is now working as expected. Thank you for your assistance!
