### ISSUE TITLE
[BUG] Text search in Azure CosmosDB fails due to the lack of diacritic sensitivity support

### ISSUE THREAD

**Issue by mykolaskrynnyk** [BeanieODM/beanie#1088]
**Describe the bug**
It is not possible to perform a full-text search on Azure Cosmos DB for MongoDB due to the fact that [diacritic sensitivity is not supported](https://learn.microsoft.com/en-us/azure/cosmos-db/mongodb/vcore/how-to-create-text-index) yet.

**To Reproduce**
```python
import asyncio
import os

from beanie import Document, Indexed, init_beanie
from beanie.operators import Text
from motor.motor_asyncio import AsyncIOMotorClient
from pymongo import TEXT


class Dish(Document):
    name: Indexed(str, index_type=TEXT)


async def example():
    client = AsyncIOMotorClient(os.environ["COSMOSDB_CONNECTION"])
    await init_beanie(database=client["test"], document_models=[Dish])
    names = [
        "Ravioli",
        "Spaghetti al pomodoro",
        "Tagliatelle al pomodoro",
    ]
    for name in names:
        dish = Dish(name=name)
        await dish.insert()

    dish = await Dish.find_one(Dish.name == "Ravioli")
    print("dish", dish)
    # dish id=ObjectId('675b131c7b21f749a28f32ff') revision_id=None name='Ravioli'
    result = await Dish.find(Text("pomodoro")).to_list()
    # pymongo.errors.OperationFailure: $diacritic insensitive searches are not supported yet
    print("result", result)


if __name__ == "__main__":
    asyncio.run(example())
```

**Expected behavior**
The code should have produced the search results for a text query, but since the [`$diacriticSensitive` is always present](https://github.com/mykolaskrynnyk/beanie/blob/0773aed151acb30dfcc4448cdbc26326c7366a53/beanie/odm/operators/find/evaluation.py#L165-L176) in the command, the search fails with

```python
pymongo.errors.OperationFailure: $diacritic insensitive searches are not supported yet, full error: {'ok': 0.0, 'errmsg': '$diacritic insensitive searches are not supported yet', 'code': 115, 'codeName': 'CommandNotSupported'}
```
**Additional context**
I will patch it up shortly.

**Comment by adeelsohailahmed** [comment]
I wouldn't classify this as a bug since Beanie doesn't explicitly support Azure's Cosmos DB, and the limitation of Cosmos DB itself doesn't constitute a bug on Beanie's end.

Nonetheless, I appreciate your contribution and bringing up this issue. Thanks!
