### ISSUE TITLE
[BUG] Incorrect type annotations for Document's `insert`, `save` and `replace`

### ISSUE THREAD

**Issue by CMHopeSunshine** [BeanieODM/beanie#679]
**Describe the bug**
when using Document.insert, save or replace
vscode pylance report an error like this:
```
Argument missing for parameter "self" Pylance(reportGeneralTypeIssues)
(method) save: _Wrapped[..., Unknown, (self: Unknown, *args: Unknown, skip_actions: List[ActionDirections | str] | None = None, **kwargs: Unknown), Coroutine[Any, Any, Unknown]]
```

I found that it was due to the incorrect type annotation of the decorator, such as `wrap_with_actions`, `save_state_after` decorator.

If I remove its type comment, it's correct.

For example:
https://github.com/roman-right/beanie/blob/main/beanie/odm/utils/state.py#L63C31

```python
def save_state_after(f: Callable):  # remove the 'Callable' annotation
    @wraps(f)
    async def wrapper(self: "DocType", *args, **kwargs):
        result = await f(self, *args, **kwargs)
        self._save_state()
        return result

    return wrapper
```

This is probably the easiest way. If we want to use annotations, I guess we need to use `ParamSpec` and `TypeVar` for more detailed annotations. For example:
```python
from functools import wraps
from typing import Callable, TypeVar
from typing_extensions import ParamSpec

P = ParamSpec("P")
R = TypeVar("R")


def example(some_arg):
    def decorator(f: Callable[P, R]) -> Callable[P, R]:
        @wraps(f)
        def wrapper(*args: P.args, **kwargs: P.kwargs):
            ...
            return f(*args, **kwargs)

        return wrapper

    return decorator

```

**To Reproduce**
```python
import asyncio

from beanie import Document, init_beanie
from motor.motor_asyncio import AsyncIOMotorClient


class Foo(Document):
    name: str


async def main():
    client = AsyncIOMotorClient("mongodb://127.0.0.1:27017/")
    await init_beanie(
        database=client.testmango,
        document_models=[Foo],
    )

    foo = Foo(name="test")
    await foo.insert()  # Argument missing for parameter "self"
    await foo.save()  # Argument missing for parameter "self"
    await foo.replace()  # Argument missing for parameter "self"


if __name__ == "__main__":
    asyncio.run(main())
```

**Expected behavior**
no error report

**Additional context**

**Comment by mozTheFuzz** [comment]
Was baffled by the error as well.
will give it a shot

**Comment by TyroneTang** [comment]
I'm also having this issue when pylance makes a highlight for `Link[Document]`

```
from beanie import Document, Link

class Content(Document):
    id: UUID = Field(default_factory=uuid4)
    publisher = str
    category = str

class Book(Document):
    id: UUID = Field(default_factory=uuid4)
    book_pub: int
    book_content: Link[Content] | None

new_content = Content(



new_book_data = Book(
      book_pub=12345, 
      book_content=

```

**Comment by helioascorreia** [comment]
I have the same issues

**Comment by jbkoh** [comment]
It seems to be due to the decorator conventions in this project. For example [this decorator](https://github.com/roman-right/beanie/blob/main/beanie/odm/utils/self_validation.py#L10).
```python
def validate_self_before(f: Callable):
    @wraps(f)
    async def wrapper(self: "DocType", *args, **kwargs):
        await self.validate_self(*args, **kwargs)
        return await f(self, *args, **kwargs)

    return wrapper
```
Because this `wrapper` is considered to be a module's function instead of a class method, self is considered to be a required positional argument, while we actually use it as a class mode from an instance.

The way to make this work better with other

**Comment by ogtega** [comment]
> However, shouldn't an instance calling a class method be considered to be the first argument always anyway?

@jbkoh tried following along with the explanation in microsoft/pyright#6472, but what did you mean in this question?

Just asking for clarification.

**Comment by jbkoh** [comment]
When you invoke `instance.method()`, `instance` is considered to be the first argument of `method`.

**Comment by jbkoh** [comment]
To close the conversation, pyright folks said that we should annotate the arguments better as described here
https://github.com/microsoft/pyright/issues/6472#issuecomment-1814022386

**Comment by TheBloke** [comment]
Anyone got any ideas how to update the decorators as per the advice from the pyright people?

I had a go, and managed to fix the "self" error.  But what I have isn't correct, because then it throws a type error on any arguments passed.

This is how I tried changing `wrap_with_actions` in `beanie/odm/actions.py` :

```py
P = ParamSpec("P")
R = TypeVar("R")
S = TypeVar("S")

def wrap_with_actions(event_type: EventTypes):
    """
    Helper function to wrap Document methods with
    before and after event listeners
    :param event_type: EventTypes - event types
    :return: None
    """

    def decorator(f: Callable[Concatenate[S, P], R]) -> Callable[Concatenate[S, P], R]:
        @wraps(f)
        async def wrapper(
            self: S,
            *args: P.args,
            skip_actions: Optional[List[Union[ActionDirections, str]]] = None,
            **kwargs: P.kwargs,
        ):
            # the rest is the same
```

But then if I try to do, for example:
```py
        return await cls(...).insert(
            link_rule=WriteRules.WRITE
        )  
```

I get type error:
```
No parameter named "link_rule"
```

Which is not correct.

I don't know enough about deep Python typing stuff to know what to do next (I didn't even know `Concatenate` was a thing before I saw this!)

**Comment by TheBloke** [comment]
Of course a big issue with the above is that `Concatenate` and `ParamSpec` require Python 3.10.  So I guess any change like the above would need to be wrapped in a check that Python >= 3.10, and wouldn't help anyone using older versions.

**Comment by bedlamzd** [comment]
> Of course a big issue with the above is that `Concatenate` and `ParamSpec` require Python 3.10. So I guess any change like the above would need to be wrapped in a check that Python >= 3.10, and wouldn't help anyone using older versions.

I'm tinkering with this a bit as well. `Concatenate` and `ParamSpec` are available in [typing_extensions](https://pypi.org/project/typing-extensions/) which is already a dependency.

I'm also trying to replace [`DocType`](https://github.com/roman-right/beanie/blob/72b35f9949989c282930492422a536899271bab3/beanie/odm/documents.py#L108) with `Self` where applicable, but it seems I found a bug in pyright because when type checking this

```python
class Document(...):
    ...

    @wrap_with_actions(EventTypes.INSERT)
    @save_state_after
    @validate_self_before
    async def insert(
        self: Self,
        *,
        link_rule: WriteRules = WriteRules.DO_NOTHING,
        session: Optional[ClientSession] = None,
        skip_actions: Optional[List[Union[ActionDirections, str]]] = None,
    ) -> Self:
        ...

    async def create(
        self: Self,
        session: Optional[ClientSession] = None,
    ) -> Self:
        """
        The same as self.insert()
        :return: Document
        """
        reveal_type(self)
        reveal_type(self.insert)
        reveal_type(self.insert(session=session))
        reveal_type(await self.insert(session=session))
        return await self.insert(session=session)
```

I get this

```shell
  /Users/bedlamzd/Repositories/beanie/beanie/odm/documents.py:372:21 - information: Type of "self" is "Self@Document"
  /Users/bedlamzd/Repositories/beanie/beanie/odm/documents.py:373:21 - information: Type of "self.insert" is "(*, link_rule: WriteRules = WriteRules.DO_NOTHING, session: ClientSession | None = None, skip_actions: List[ActionDirections | str] | None = None) -> Coroutine[Any, Any, Document]"
  /Users/bedlamzd/Repositories/beanie/beanie/odm/documents.py:374:21 - information: Type of "self.insert(session=session)" is "Coroutine[Any, Any, Document]"
  /Users/bedlamzd/Repositories/beanie/beanie/odm/documents.py:375:21 - information: Type of "await self.insert(session=session)" is "Document"
  /Users/bedlamzd/Repositories/beanie/beanie/odm/documents.py:376:16 - error: Expression of type "Document" cannot be assigned to return type "Self@Document"
    Type "Document" cannot be assigned to type "Self@Document" (reportReturnType)

```

I don't see a reason why pyright thinks `insert` returns strict `Document` instead of `Self@Document`

**Comment by TheBloke** [comment]
> I'm tinkering with this a bit as well. Concatenate and ParamSpec are available in [typing_extensions](https://pypi.org/project/typing-extensions/) which is already a dependency.

Oh yes, great point! I forgot about that.

So are you already working on a PR for this? I won't do one if you already have one you're working on.

**Comment by bedlamzd** [comment]
> > I'm tinkering with this a bit as well. Concatenate and ParamSpec are available in [typing_extensions](https://pypi.org/project/typing-extensions/) which is already a dependency.
> 
> Oh yes, great point! I forgot about that.
> 
> So are you already working on a PR for this? I won't do one if you already have one you're working on.

I don't have a PR for this, so you can go ahead if you have something ready. I just stumbled upon this yesterday and thought it'd be interesting to look around.

But I can start working on a PR, I think I'm almost done with the decorators. The only thing left is to annotate async cases properly

**Comment by bedlamzd** [comment]
FYI I've opened a PR for this issue https://github.com/roman-right/beanie/pull/886

Sorry it took few days, got distracted

**Comment by staticxterm** [comment]
Similarly to #807, we'll also be closing this one and tracking the remaining typing issues in #696.
Thank you for the report!
