### ISSUE TITLE
[BUG] (docs) migrations *have* to specify a `-db` argument, even if it's included in the db string?

### ISSUE THREAD

**Issue by ldorigo** [BeanieODM/beanie#851]
The docs at  https://beanie-odm.dev/tutorial/migrations/ show a few different invocations for the `migrate` command. In some the `db` name is included in the url string only, in others it's passed explicitly to the `-db` argument - after a bunch of debugging, it seems like only passing it in the uri string doesn't work, the docs should reflect this fact.

**Comment by roman-right** [comment]
Good catch! Thank you
