### ISSUE TITLE
[BUG]before_event bug 

### ISSUE THREAD

**Issue by CAPITAINMARVEL** [BeanieODM/beanie#902]
class Sample(Document):
    num: int
    name: str
    version: int = 0

    @before_event(Update)
    def increase_version(self):
        self.version += 1

doc = await Sample.find_one()
await doc.inc({Sample.num: 1})

i looked in database num increase so its clearly updated
but the versioning is never changing

**Comment by roman-right** [comment]
Hi @CAPITAINMARVEL ,
Unfortunately it would be tricky and not explicit enough to add an addition set step to the update query for this case
