### ISSUE TITLE
[BUG] `PydanticObjectId` isn't properly configured when deserializing from JSON

### ISSUE THREAD

**Issue by hongyiweiwu01** [BeanieODM/beanie#940]
**Describe the bug**
Consider the following code:
```python
class A(BaseModel):
   id: PydanticObjectId

raw = '{"id": "5eb7cf5a86d9755df3a6c593"}'
deserialized = A.model_validate_json(raw)
```

One would expect `type(deserialized.id) == PydanticObjectId`, but it's actually deserialized to `str`.

**To Reproduce**
See example above.

**Expected behavior**
`type(deserialized.id)` should be `PydanticObjectId`.

**Additional context**
Note that if I do `A.model_validate(json.loads(raw))` the code works. This is potentially because in the [`__get_pydantic_core_schema__` override in `PydanticObjectId`](https://github.com/BeanieODM/beanie/blob/main/beanie/odm/fields.py#L146), `python_schema` includes a transformation of the id from `str` to `ObjectId`, while the `json_schema` doesn't and directly uses the built-in `str_schema`.

**Comment by hd10180** [comment]
try this. maybe is a solution.

```python
import json
from beanie import PydanticObjectId

from pydantic import BaseModel


class A(BaseModel):
    id: PydanticObjectId


raw = '{"id": "5eb7cf5a86d9755df3a6c593"}'
# deserialized = A.model_validate_json(raw)
deserialized = A(**json.loads(raw))
print(deserialized)  # > id=ObjectId('5eb7cf5a86d9755df3a6c593')
print(type(deserialized.id)) # > <class 'beanie.odm.fields.PydanticObjectId'>
```

**Comment by ivan-gj** [comment]
Hello. This bug exists. It's quite critical, to be honest. Please reopen.
