### ISSUE TITLE
depth search "find(Teste.item1.item2.item3.id == id)" [BUG]

### ISSUE THREAD

**Issue by deivisonmarteleto** [BeanieODM/beanie#943]
Olá!

using "find(Teste.item1.item.2.item3.id == id)" , I noticed that when it goes 2 levels deep, item3.id only searches if searched with item3._id

up to level 2 item2.id is search done by id...

**Comment by Diegovsky** [comment]
I noticed this happens too. I'm having a hard time searching the database because of this.
