### ISSUE TITLE
[BUG] DeleteRules.DELETE_LINKS is not working?

### ISSUE THREAD

**Issue by dinhtuanan** [BeanieODM/beanie#971]
**Describe the bug**
DeleteRules.DELETE_LINKS is not working. Delete a document success but all linked document didn't

**To Reproduce**
```python
import asyncio
from typing import Optional

from beanie import BackLink, Document, Link, init_beanie
from beanie.odm.utils.encoder import Encoder
from motor.motor_asyncio import AsyncIOMotorClient
from pydantic import Field

from beanie import DeleteRules, WriteRules

class Person(Document):
    name: str
    age: int
    cars: list[Link["Car"]] = Field(default_factory=list)


class Car(Document):
    manufacturer: str
    price: float
    owner: Optional[BackLink[Person]] = Field(default=None, original_field="cars")


async def init():
    client = AsyncIOMotorClient(
        "mongodb://localhost:27017",
    )

    await init_beanie(database=client.test_db, document_models=[Person, Car])

    p1 = Person(
        name="John",
        age=25,
    )    
    p1.cars = [
        Car(manufacturer="Toyota", price=10000),
        Car(manufacturer="BMW", price=20000)
    ]
    await p1.save(link_rule=WriteRules.WRITE)
    # The above code runs fine
    
    person = await Person.find_one(Person.name == "John")
    print(person)
    
    # Only person document is deleted, cars didn't
    await person.delete(link_rule=DeleteRules.DELETE_LINKS)

asyncio.run(init())
```

**Expected behavior**
- Document and all linked document will be deleted

**Additional context**
- Maybe I misunderstood how it works. Can you explain it?

**Comment by NuxitBrain** [comment]
Hi ! did you check our car document and if something change inside ? For me ( and maybe i didn't understand) the delete rule just delete the link and not the document. So if you delete the car document, the field cars inside your car document should set to null... Someone can confirm that ?

**Comment by deivisonmarteleto** [comment]
The import method is not correct. Try it like this:

**from beanie.odm.fields import DeleteRules**

**Comment by hadware** [comment]
I'm having the same issue, anyone have a solution for this?

**Comment by staticxterm** [comment]
Not sure if this is a bug exactly. The provided repro code reproduces the issue, but the problem is that on line that retrieves the person object, the links are not fetched:
`person = await Person.find_one(Person.name == "John")`
It works if the links are fetched first (using `fetch_links=True`), or if the action is executed on the `p1` object still in memory.
