### ISSUE TITLE
[BUG] fetch_links error

### ISSUE THREAD

**Issue by freshchen** [BeanieODM/beanie#974]
**Describe the bug**
I get an error when I try to use the link function

**To Reproduce**
```python
class Ref(Document):
    url: str

    class Settings:
        name = "refs"


class Project(Document):
    name: str
    ref: Link[Ref]

    class Settings:
        name = "projects"

p1 = await Project.find_one(Project.name == "Project1", fetch_links=True)
```

**Expected behavior**
/Library/Caches/pypoetry/virtualenvs/local-py-CjjAPjKL-py3.11/lib/python3.11/site-packages/pymongo/helpers.py", line 248, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: Unrecognized pipeline stage name: '$set', full error: {'ok': 0.0, 'errmsg': "Unrecognized pipeline stage name: '$set'", 'code': 40324, 'codeName': 'Location40324'}

**Additional context**
mac
beanie==1.26.0
py311

**Comment by Ray-Escobar** [comment]
did you initalize beanie, and initialized the collections properly? this should work if you set the collections correctly

**Comment by freshchen** [comment]
It seems to have been fixed after I updated the version

**Comment by vijayrai-capri** [comment]
I am facing this issue with Amazon DocumentDB, if i change the db to mongodb on my local it works fine with the same code.

**Comment by whitfin** [comment]
This was opened in Bunnet for DocumentDB compatibility: https://github.com/BeanieODM/bunnet/pull/19

I wonder if this needs pulling into this library.
